version: 2
updates:
  - package-ecosystem: "maven"
    directories: 
      - "/"
      - "/rtp"
      - "/jitsi-media-transform"
      - "/jvb"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
