#!/bin/sh
# prerm script for jitsi-videobridge

set -e

case "$1" in
    remove|purge)
    ;;

    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
