/*
 * Copyright @ 2018 - present 8x8, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jitsi.nlj

import org.jitsi.nlj.rtp.VideoRtpPacket
import org.jitsi.nlj.util.Bandwidth
import org.jitsi.nlj.util.bps
import org.jitsi.rtp.rtp.RtpPacket
import org.jitsi.utils.ArrayUtils
import java.util.Collections
import java.util.NavigableMap
import java.util.TreeMap

/**
 * Represents a collection of [RtpLayerDesc]s that encode the same
 * media source. This specific implementation provides webrtc simulcast stream
 * suspension detection.
 *
 * We take the definition of "Media Source" from RFC 7656.  It takes a single
 * logical source of media, which might be represented by multiple encoded streams.
 *
 * @author George Politis
 */
class MediaSourceDesc
@JvmOverloads constructor(
    /**
     * The [RtpEncodingDesc]s that this [MediaSourceDesc]
     * possesses, ordered by their subjective quality from low to high.
     * Each is at the index of its encoding ID, [RtpEncodingDesc.eid].
     */
    val rtpEncodings: Array<RtpEncodingDesc>,
    /**
     * A string which identifies the owner of this source (e.g. the endpoint
     * which is the sender of the source).
     */
    val owner: String,
    /**
     * A string which identifies this source.
     */
    val sourceName: String,
    /**
     * The {@link VideoType} signaled for this media source (defaulting to {@code CAMERA} if nothing has been signaled).
     */
    videoType: VideoType = VideoType.CAMERA,
    /**
     * Whether this is a synthetic source, i.e. one generated by the bridge rather than sent by an endpoint.
     */
    val synthetic: Boolean = false,
) {
    /**
     * Current single-list view of all the encodings' layers.
     */
    private lateinit var layers: List<RtpLayerDesc>

    /**
     * Allow the lookup of a layer by the encoding id of a received packet.
     */
    private val layersById: MutableMap<Long, RtpLayerDesc> = HashMap()

    /**
     * Allow the lookup of a layer by index.
     */
    private val layersByIndex: NavigableMap<Int, RtpLayerDesc> = TreeMap()

    /**
     * Get a view of the source's RTP layers, in quality order.
     */
    val rtpLayers: List<RtpLayerDesc>
        @Synchronized
        get() = layers

    /**
     * Update the layer cache.  Should be synchronized on [this].
     */
    private fun updateLayerCache() {
        layersById.clear()
        layersByIndex.clear()
        val tempLayers = ArrayList<RtpLayerDesc>()

        for (encoding in rtpEncodings) {
            for (layer in encoding.layers) {
                layersById[encoding.encodingId(layer)] = layer
                layersByIndex[layer.index] = layer
                tempLayers.add(layer)
            }
        }
        layers = Collections.unmodifiableList(tempLayers)
    }

    init {
        rtpEncodings.forEachIndexed { index, encoding ->
            require(encoding.eid == index) { "Encoding with EID ${encoding.eid} at index $index" }
        }
        updateLayerCache()
    }

    /**
     * The [VideoType] signaled for this media source (defaulting to [VideoType.CAMERA] if nothing has been signaled).
     * Setting it sets the liveness timeout of each of the source's encodings to the timeout for its type, see
     * [EncodingLivenessTracker.timeoutMs].
     */
    var videoType: VideoType = videoType
        set(value) {
            field = value
            setLivenessTimeouts(value)
        }

    init {
        setLivenessTimeouts(videoType)
    }

    /** Sets the liveness timeout of each of this source's encodings to the timeout for a source of [type]. */
    private fun setLivenessTimeouts(type: VideoType) {
        val timeoutMs = type.livenessTimeoutMs()
        rtpEncodings.forEach { it.liveness.timeoutMs = timeoutMs }
    }

    /**
     * Gets the last "stable" bitrate (in bps) of the encoding of the specified
     * index. The "stable" bitrate is measured on every new frame and with a
     * 5000ms window.
     *
     * If the bitrate for the specified index is 0, return bitrate of the highest-
     * index layer less than the index with a non-zero bitrate.
     *
     * @return the last "stable" bitrate (bps) of the encoding with a non-zero rate
     * at or below the specified index.
     */
    @Synchronized
    fun getBitrate(nowMs: Long, idx: Int): Bandwidth {
        for (entry in layersByIndex.headMap(idx, true).descendingMap()) {
            val bitrate = entry.value.getBitrate(nowMs)
            if (bitrate.bps > 0) {
                return bitrate
            }
        }
        return 0.bps
    }

    @Synchronized
    fun hasRtpLayers(): Boolean = layers.isNotEmpty()

    @Synchronized
    fun numRtpLayers(): Int = layersByIndex.size

    val primarySSRC: Long
        get() = rtpEncodings[0].primarySSRC

    @Synchronized
    fun getRtpLayerByQualityIdx(idx: Int): RtpLayerDesc? = layersByIndex[idx]

    @Synchronized
    fun findRtpLayerDescs(videoRtpPacket: VideoRtpPacket): Collection<RtpLayerDesc> {
        if (ArrayUtils.isNullOrEmpty(rtpEncodings)) {
            return emptyList()
        }
        return videoRtpPacket.getEncodingIds().mapNotNull { layersById[it] }
    }

    @Synchronized
    fun findRtpEncodingDesc(ssrc: Long): RtpEncodingDesc? = rtpEncodings.find { it.hasSsrc(ssrc) }

    /** The encoding of this source with encoding ID [eid], if any. */
    fun getRtpEncodingByEid(eid: Int): RtpEncodingDesc? = rtpEncodings.getOrNull(eid)

    /**
     * When the most recent media packet of any encoding of this source was received, or
     * [EncodingLivenessTracker.NEVER_RECEIVED]. This is the time as of which what is known about the encodings'
     * liveness is current. Code which judges liveness with no packet of its own uses this rather than the wall clock.
     * That way a delay in processing does not make every encoding look stopped. While nothing is heard from the
     * sender, the last known state is kept.
     */
    val lastPacketReceivedMs: Long
        get() {
            var last = EncodingLivenessTracker.NEVER_RECEIVED
            for (encoding in rtpEncodings) {
                last = maxOf(last, encoding.liveness.lastPacketReceivedMs)
            }
            return last
        }

    /** Whether the encoding with encoding ID [eid] is currently being sent, see [EncodingLivenessTracker.isLive]. */
    fun isEncodingLive(eid: Int, nowMs: Long): Boolean = getRtpEncodingByEid(eid)?.liveness?.isLive(nowMs) ?: false

    /** The primary SSRCs of the encodings currently being sent, see [EncodingLivenessTracker.isLive]. */
    fun liveEncodingSsrcs(nowMs: Long): List<Long> =
        rtpEncodings.filter { it.liveness.isLive(nowMs) }.map { it.primarySSRC }

    /**
     * Whether the encoding with encoding ID [eid] kept being sent while the encoding with encoding ID [otherEid]
     * stopped, see [EncodingLivenessTracker.hasOutlasted].
     */
    fun hasEncodingOutlasted(eid: Int, otherEid: Int, nowMs: Long): Boolean {
        val other = getRtpEncodingByEid(otherEid) ?: return false
        return getRtpEncodingByEid(eid)?.liveness?.hasOutlasted(other.liveness, nowMs) ?: false
    }

    /**
     * The encoding a receiver whose target is the layer with index [targetIndex] can actually be switched to now. That
     * encoding is the highest live encoding at or below the target's encoding. Null if the target is suspended, or if
     * no encoding at or below it is live. This is the encoding whose keyframe such a receiver should wait for, and
     * request. It is below the target when the sender has turned the target encoding off, whether on its own or in
     * response to the bridge's signaling. The encoding's bitrate measurement would only show that several seconds
     * later.
     *
     * This is [effectiveTargetEid] applied to this source's encodings, with one difference. When nothing at or below
     * the target is live, this returns null, so that the caller requests a keyframe from the source's primary SSRC.
     * That is the only request a sender which has stopped every encoding could answer. The quality filters use
     * [effectiveTargetEid] directly and keep wanting the target in that case, so that they keep needing a keyframe.
     *
     * Called for every packet of a source while a receiver is waiting for a keyframe, so it does not allocate.
     */
    fun getEffectiveTargetEncoding(targetIndex: Int, nowMs: Long): RtpEncodingDesc? {
        if (targetIndex == RtpLayerDesc.SUSPENDED_INDEX) {
            return null
        }
        /* The search reports whether it found a live encoding, so that liveness is read once per encoding. The lambda
         * is inlined, so capturing the flag allocates nothing. */
        var found = false
        val eid = effectiveTargetEid(RtpLayerDesc.getEidFromIndex(targetIndex)) { candidate ->
            isEncodingLive(candidate, nowMs).also { live -> if (live) found = true }
        }
        return if (found) getRtpEncodingByEid(eid) else null
    }

    companion object {
        /**
         * The encoding a receiver wanting encoding [targetEid] should be trying to reach. That is the highest encoding
         * at or below it for which [isLive] is true, or [targetEid] itself if there is none. Encodings are numbered
         * from 0 in order of quality. Inline, so that it allocates nothing when called with a lambda.
         */
        inline fun effectiveTargetEid(targetEid: Int, isLive: (Int) -> Boolean): Int {
            if (targetEid < 0) {
                return targetEid
            }
            for (eid in targetEid downTo 0) {
                if (isLive(eid)) {
                    return eid
                }
            }
            return targetEid
        }
    }

    @Synchronized
    fun getEncodingLayers(ssrc: Long): Array<RtpLayerDesc> {
        val enc = findRtpEncodingDesc(ssrc) ?: return emptyArray()
        return Array(enc.layers.size) { i ->
            enc.layers[i].copy()
        }
    }

    @Synchronized
    fun setEncodingLayers(layers: Array<RtpLayerDesc>, ssrc: Long) {
        val enc = findRtpEncodingDesc(ssrc) ?: return
        enc.layers = layers
        updateLayerCache()
    }

    /**
     * Clone an existing media source desc, inheriting layer descs' statistics.
     */
    @Synchronized
    fun copy() = MediaSourceDesc(
        Array(this.rtpEncodings.size) { i -> this.rtpEncodings[i].copy() },
        this.owner,
        this.sourceName,
        this.videoType,
        this.synthetic
    )

    override fun toString(): String = "MediaSourceDesc[name=$sourceName owner=$owner, videoType=$videoType, " +
        "synthetic=$synthetic, encodings=${rtpEncodings.joinToString(",")}]"

    /**
     * Checks whether the given SSRC matches this source's [primarySSRC].
     * This is mostly useful only for determining quickly whether two source
     * descriptions describe the same source; other functions (probably [hasSsrc]) should be used
     * to match received media packets.
     *
     * @param ssrc the SSRC to match.
     * @return `true` if the specified `ssrc` is the primary SSRC
     * for this source.
     */
    fun matches(ssrc: Long) = rtpEncodings.getOrNull(0)?.primarySSRC == ssrc

    /**
     * Checks whether any encoding of this source has this [ssrc]
     */
    @Synchronized
    fun hasSsrc(ssrc: Long) = rtpEncodings.any { it.hasSsrc(ssrc) }
}

/**
 * Clone an array of media source descriptions.
 */
fun Array<MediaSourceDesc>.copy() = Array(this.size) { i -> this[i].copy() }

fun Array<MediaSourceDesc>.findRtpLayerDescs(packet: VideoRtpPacket): Collection<RtpLayerDesc> = this.flatMap {
    it.findRtpLayerDescs(packet)
}

fun Array<MediaSourceDesc>.findRtpSourceByPrimary(ssrc: Long): MediaSourceDesc? = this.find { it.matches(ssrc) }

fun Array<MediaSourceDesc>.findRtpSource(ssrc: Long): MediaSourceDesc? = this.find { it.hasSsrc(ssrc) }

/**
 * The liveness timeout for a source of this video type, in milliseconds, see [EncodingLivenessTracker.timeoutMs]:
 * the desktop timeout for any screen share, the camera timeout otherwise.
 */
private fun VideoType.livenessTimeoutMs(): Long =
    (if (isScreenshare()) EncodingLivenessConfig.desktopTimeout else EncodingLivenessConfig.cameraTimeout).toMillis()

/** An encoding of a source, as looked up by one of its SSRCs. */
class SourceEncoding(val source: MediaSourceDesc, val encoding: RtpEncodingDesc)

/**
 * Indexes the sources' encodings by every SSRC of each, primary and secondary, for code which looks an encoding up
 * for every packet or keyframe.
 */
fun Array<MediaSourceDesc>.indexEncodingsBySsrc(): Map<Long, SourceEncoding> = flatMap { source ->
    source.rtpEncodings.flatMap { encoding -> encoding.ssrcs.map { ssrc -> ssrc to SourceEncoding(source, encoding) } }
}.toMap()

fun Array<MediaSourceDesc>.findRtpSource(packet: RtpPacket): MediaSourceDesc? = findRtpSource(packet.ssrc)

fun Array<MediaSourceDesc>.findRtpEncodingId(packet: VideoRtpPacket): Int? {
    for (source in this) {
        source.findRtpEncodingDesc(packet.ssrc)?.let {
            return it.eid
        }
    }
    return null
}
