.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH JITSI-VIDEOBRIDGE SECTION "April 09, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
jitsi-videobridge \- WebRTC compatible Selective Forwarding Unit 
(SFU) for multiuser video communication
.SH SYNOPSIS
.B /usr/share/jitsi-videobridge/jvb.sh
.RI [ options ] ...
.br
.B /etc/init.d/jitsi-videobridge (start|stop|restart)
.SH DESCRIPTION
This manual page documents briefly the
.B jitsi-videobridge
service.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invoke bold face and italics,
.\" respectively.
\fBjitsi-videobridge\fP is a Selective Forwarding Unit (SFU) for 
building applications for WebRTC compatible video conferences.
.SH AUTHOR
jitsi-videobridge was written by Jitsi.org and Bluejimp.com.
.PP
This manual page was written by Yasen Pramatarov <yasen@bluejimp.com>,
for the Debian project (and may be used by others).
