/*
 * Copyright @ 2018 - present 8x8, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jitsi.videobridge.relay

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Description of an audio source, parallel to [MediaSourceDesc] which is just for video.
 * TODO: these should be made more parallel and share a common base class, probably.
 */
data class AudioSourceDesc(
    val ssrc: Long,
    val owner: String? = null,
    val sourceName: String? = null,
    /** Whether this is a synthetic source, i.e. one generated by the bridge rather than sent by an endpoint. */
    val synthetic: Boolean = false,
    /** What kind of synthetic source this is; null if it is not synthetic, or if the kind is not known. */
    val kind: SyntheticSourceKind? = null
) {
    init {
        require(kind == null || synthetic) { "Only a synthetic source has a kind" }
    }
}

/**
 * The kind of a synthetic audio source. Signaled to clients on the bridge channel (as the lowercase wire name) so
 * they can tell the kinds apart without inspecting source names.
 */
enum class SyntheticSourceKind {
    /** A voice agent's injected audio, owned by a synthetic endpoint (one with no media transport of its own). */
    @JsonProperty("agent")
    AGENT,

    /** Translated audio, owned by the regular endpoint whose audio it is a translation of. */
    @JsonProperty("translation")
    TRANSLATION;

    companion object {
        /**
         * The kind of a synthetic source given whether the endpoint owning it is synthetic, or null when that is
         * not known.
         */
        fun forOwner(ownerSynthetic: Boolean?): SyntheticSourceKind? = when (ownerSynthetic) {
            true -> AGENT
            false -> TRANSLATION
            null -> null
        }
    }
}
